<?php
function page_head(string $title, string $description, string $path = ''): void { $title=str_replace(["Ellen's Florist",'Ellen’s Florist','Ellen Florist'],'Ellens Florist',$title); $description=str_replace(["Ellen's Florist",'Ellen’s Florist','Ellen Florist'],'Ellens Florist',$description); $canonical=url($path); ?>
<!doctype html><html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="description" content="<?=e($description)?>"><meta name="keywords" content="premium florist, wedding flowers, wedding decoration, Bali florist, Indonesia"><meta name="theme-color" content="#E0B84F">
<link rel="canonical" href="<?=e($canonical)?>"><meta property="og:type" content="website"><meta property="og:title" content="<?=e($title)?>"><meta property="og:description" content="<?=e($description)?>"><meta property="og:url" content="<?=e($canonical)?>"><meta name="twitter:card" content="summary_large_image">
<title><?=e($title)?></title><link rel="icon" type="image/png" href="/assets/images/favicon.png"><link rel="apple-touch-icon" href="/assets/images/favicon.png"><link rel="stylesheet" href="/assets/css/main.css"><script type="application/ld+json">{"@context":"https://schema.org","@graph":[{"@type":"Florist","name":"Ellens Florist","url":"https://ellensflorist.com","telephone":"+62","openingHours":"Mo-Su 09:00-20:00","sameAs":["https://www.instagram.com/ellensflorist.id/","https://wa.link/s50rb5"]},{"@type":"WebSite","name":"Ellens Florist","url":"https://ellensflorist.com"}]}</script></head><body>
<a class="skip" href="#main">Skip to content</a><header class="site-header"><a class="brand" href="/"><img src="/assets/images/logo.png" alt="Ellens Florist logo"><span><b>Ellens Florist</b><small>Blooms that tell your story</small></span></a><button class="menu-toggle" aria-expanded="false" aria-controls="main-nav">Menu</button><nav id="main-nav" aria-label="Main navigation"><a href="/about">About</a><a href="/wedding">Weddings</a><a href="/gallery">Gallery</a><a href="/how-to-order">How to order</a><a href="/blog">Journal</a><a href="/contact">Contact</a><a class="nav-cta" href="/wedding-inquiry">Start your inquiry</a></nav><div class="shop-clock"><small>Current time in our shop</small><time data-shop-clock>--:--:--</time><em>WITA (UTC+8)</em></div></header>
<?php }
function page_footer(): void { ?><footer><section class="footer-cta"><p class="eyebrow">Your story, beautifully told</p><h2>Let's create flowers worth remembering.</h2><a class="button gold" href="/wedding-inquiry">Plan your wedding florals</a></section><div class="footer-grid"><div><a class="brand" href="/"><img src="/assets/images/logo.png" alt="Ellens Florist logo"><span><b>Ellens Florist</b></span></a><p>Artful florals and thoughtful celebration styling, made to feel unmistakably yours.</p><p><strong>Visits are strictly by appointment only.</strong><br>Customer service: 09:00–20:00 WITA</p></div><div><h3>Explore</h3><a href="/wedding">Wedding services</a><a href="/wedding-decoration">Decoration</a><a href="/gallery">Gallery</a><a href="/faq">FAQ</a></div><div><h3>Connect</h3><a href="https://www.instagram.com/ellensflorist.id/" target="_blank" rel="noopener">Instagram</a><a href="https://wa.link/s50rb5" target="_blank" rel="noopener">WhatsApp</a><a href="/contact">Contact us</a><a href="/privacy-policy">Privacy</a><a href="/terms">Terms</a></div></div><div class="copyright">© <?=date('Y')?> Ellens Florist <span>Made with love by PT VIRATAMA FLORA INDONESIA</span></div></footer><a class="whatsapp" href="https://wa.link/s50rb5" aria-label="Chat with Ellens Florist on WhatsApp" target="_blank" rel="noopener">✆ <span>WhatsApp</span></a><script src="/assets/js/main.js" defer></script></body></html><?php }
