-- Import after schema.sql. Every record can be changed in Admin > Content library.
INSERT INTO content (type,title,slug,excerpt,body,image_path,status,meta_title,meta_description,published_at) VALUES
('gallery','Ivory Garden Reception','ivory-garden-reception','A soft, candlelit wedding reception in ivory, blush, and champagne tones.','<p>A considered tablescape of garden roses, orchids, taper candles, and quiet, romantic texture.</p>','/assets/images/cassy-reception.webp','published','Ivory Garden Reception | Ellens Florist','Elegant ivory and blush wedding reception flowers.',NOW()),
('gallery','Blush Ceremony Moment','blush-ceremony-moment','A romantic floral ceremony concept for an intimate Bali celebration.','<p>A floral ceremony framed by the Bali landscape.</p>','/assets/images/claire-ceremony.webp','published','Blush Ceremony Moment | Ellens Florist','Romantic floral ceremony styling by Ellens Florist.',NOW()),
('gallery','Golden Hour Tablescape','golden-hour-tablescape','Warm candles and layered flowers designed for unforgettable toasts.','<p>Beautiful reception details for a relaxed garden celebration.</p>','/assets/images/chloe-ceremony.webp','published','Golden Hour Tablescape | Ellens Florist','Luxury wedding table flowers by Ellens Florist.',NOW()),
('gallery','Modern Garden Romance','modern-garden-romance','A fresh blend of sculptural orchids, garden roses, and soft green foliage.','<p>Softly layered flowers with a relaxed, personal feel.</p>','/assets/images/cassy-bouquet.webp','published','Modern Garden Romance | Ellens Florist','Modern garden wedding flowers.',NOW()),
('gallery','Dinner Under Flowers','dinner-under-flowers','An immersive floral installation created for an evening of celebration.','<p>A ceremony setting designed for a memorable wedding day.</p>','/assets/images/claire-reception.webp','published','Dinner Under Flowers | Ellens Florist','Luxury floral installation by Ellens Florist.',NOW()),
('post','Choosing flowers for your wedding season','choosing-wedding-flowers-by-season','A thoughtful guide to building a floral palette that feels naturally beautiful in every season.','<p>Seasonality helps create a design that feels alive, personal, and effortless.</p>','/assets/images/cassy-ceremony.webp','published','Choosing Wedding Flowers by Season | Ellens Florist','Wedding flower inspiration from Ellens Florist.',NOW()),
('post','How to make reception tables memorable','memorable-wedding-reception-tables','The small floral and styling decisions that help a reception feel generous and unforgettable.','<p>Beautiful tables begin with feeling: texture, candlelight, conversation, and space for guests to connect.</p>','/assets/images/chloe-reception.webp','published','Memorable Wedding Reception Tables | Ellens Florist','Reception flower inspiration from Ellens Florist.',NOW()),
('post','Our guide to a considered bridal bouquet','considered-bridal-bouquet','Find the shape, flower mix, and personality that feel entirely like you.','<p>Your bouquet should feel effortless in your hands and unmistakably yours.</p>','/assets/images/cassy-bouquet.webp','published','A Considered Bridal Bouquet | Ellens Florist','Bridal bouquet advice from Ellens Florist.',NOW()),
('testimonial','Claudia & Raka · Indonesia','claudia-raka-review','Every arrangement felt like it belonged to us. The venue was transformed into something beyond what we imagined.','','','published','Claudia and Raka Review | Ellens Florist','Client review for Ellens Florist.',NOW()),
('testimonial','Marissa & Daniel · Singapore','marissa-daniel-review','The team understood our vision immediately and made planning from abroad feel effortless.','','','published','Marissa and Daniel Review | Ellens Florist','Client review for Ellens Florist.',NOW()),
('testimonial','Ayu & Bima · Indonesia','ayu-bima-review','Elegant, warm, and incredibly detailed. Our guests are still talking about the flowers.','','','published','Ayu and Bima Review | Ellens Florist','Client review for Ellens Florist.',NOW()),
('testimonial','Sophie & James · Australia','sophie-james-review','The installation was breathtaking and the team were absolute professionals.','','','published','Sophie and James Review | Ellens Florist','Client review for Ellens Florist.',NOW()),
('testimonial','Nadia & Kevin · Indonesia','nadia-kevin-review','They turned a simple venue into something magical. We could not recommend them more.','','','published','Nadia and Kevin Review | Ellens Florist','Client review for Ellens Florist.',NOW()),
('testimonial','Maya & Ethan · United Kingdom','maya-ethan-review','Truly bespoke flowers and wonderful communication from start to finish.','','','published','Maya and Ethan Review | Ellens Florist','Client review for Ellens Florist.',NOW());
