-- Import after schema.sql. Every record can be changed in Admin > Content library.
INSERT INTO content (type,title,slug,excerpt,body,image_path,status,meta_title,meta_description,published_at) VALUES
('gallery','Mega & Will Ceremony','mega-will-ceremony','A joyous tropical wedding ceremony in Bali.','<p>Natural textures, ceremony flowers, and a beautiful oceanfront setting.</p>','/assets/images/mega-will-ceremony.webp','published','Mega & Will Ceremony | Ellens Florist','Bali wedding ceremony flowers by Ellens Florist.',NOW()),
('gallery','Mega & Will Reception','mega-will-reception','A warm reception scene designed for an unforgettable celebration.','<p>Thoughtful flowers and styling that invite guests to relax and celebrate.</p>','/assets/images/mega-will-reception.webp','published','Mega & Will Reception | Ellens Florist','Wedding reception styling by Ellens Florist.',NOW()),
('gallery','Mega & Will Floral Details','mega-will-floral-details','Close-up floral moments full of texture and colour.','<p>Every arrangement is made to feel personal to the couple and their setting.</p>','/assets/images/mega-will-details.webp','published','Mega & Will Floral Details | Ellens Florist','Bali wedding floral details by Ellens Florist.',NOW()),
('gallery','Mega & Will Tablescape','mega-will-tablescape','An airy tablescape made for long conversations and joyful toasts.','<p>Layered florals and considered details bring the table to life.</p>','/assets/images/mega-will-table.webp','published','Mega & Will Tablescape | Ellens Florist','Wedding tablescape styling by Ellens Florist.',NOW()),
('gallery','Mega & Will Celebration','mega-will-celebration','A candid moment from a celebration designed with warmth and movement.','<p>Florals and styling that feel as natural as the people celebrating together.</p>','/assets/images/mega-will-dance.webp','published','Mega & Will Celebration | Ellens Florist','Wedding celebration flowers by Ellens Florist.',NOW()),
('post','Choosing flowers for your wedding season','choosing-wedding-flowers-by-season','A thoughtful guide to building a floral palette that feels naturally beautiful in every season.','<p>Seasonality helps create a design that feels alive, personal, and effortless.</p>','/assets/images/mega-will-ceremony.webp','published','Choosing Wedding Flowers by Season | Ellens Florist','Wedding flower inspiration from Ellens Florist.',NOW()),
('post','How to make reception tables memorable','memorable-wedding-reception-tables','The small floral and styling decisions that help a reception feel generous and unforgettable.','<p>Beautiful tables begin with feeling: texture, candlelight, conversation, and space for guests to connect.</p>','/assets/images/mega-will-reception.webp','published','Memorable Wedding Reception Tables | Ellens Florist','Reception flower inspiration from Ellens Florist.',NOW()),
('post','Our guide to a considered bridal bouquet','considered-bridal-bouquet','Find the shape, flower mix, and personality that feel entirely like you.','<p>Your bouquet should feel effortless in your hands and unmistakably yours.</p>','/assets/images/jisoo-sabrina-ceremony.webp','published','A Considered Bridal Bouquet | Ellens Florist','Bridal bouquet advice from Ellens Florist.',NOW()),
('testimonial','Claudia & Raka · Indonesia','claudia-raka-review','Every arrangement felt like it belonged to us. The venue was transformed into something beyond what we imagined.','','','published','Claudia and Raka Review | Ellens Florist','Client review for Ellens Florist.',NOW()),
('testimonial','Marissa & Daniel · Singapore','marissa-daniel-review','The team understood our vision immediately and made planning from abroad feel effortless.','','','published','Marissa and Daniel Review | Ellens Florist','Client review for Ellens Florist.',NOW()),
('testimonial','Ayu & Bima · Indonesia','ayu-bima-review','Elegant, warm, and incredibly detailed. Our guests are still talking about the flowers.','','','published','Ayu and Bima Review | Ellens Florist','Client review for Ellens Florist.',NOW()),
('testimonial','Sophie & James · Australia','sophie-james-review','The installation was breathtaking and the team were absolute professionals.','','','published','Sophie and James Review | Ellens Florist','Client review for Ellens Florist.',NOW()),
('testimonial','Nadia & Kevin · Indonesia','nadia-kevin-review','They turned a simple venue into something magical. We could not recommend them more.','','','published','Nadia and Kevin Review | Ellens Florist','Client review for Ellens Florist.',NOW()),
('testimonial','Maya & Ethan · United Kingdom','maya-ethan-review','Truly bespoke flowers and wonderful communication from start to finish.','','','published','Maya and Ethan Review | Ellens Florist','Client review for Ellens Florist.',NOW());
